apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.tampilator.editorfoto'
    compileSdk 34

    defaultConfig {
        applicationId "com.tampilator.editorfoto"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}
